server:
  port: 2001
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false #
      routes:
      - id: path_route
        uri: http://qmaolong.cn
        predicates:
        - Path=/aa
      - id: client-1
        uri: lb://eureka-client-1
        predicates:
        - Path=/user/**
      - id: client-2
        uri: lb://eureka-client-2
        predicates:
        - Path=/client2/**
# Eureka Server 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/